#!/bin/bash

echo "🚀 CloudBase完整解决方案"
echo "========================"
echo ""

echo "📋 当前状态检查..."
cloudbase functions:list

echo ""
echo "🔧 解决方案1: 通过CloudBase控制台配置HTTP触发器"
echo "================================================"
echo ""
echo "1. 访问CloudBase控制台："
echo "   https://console.cloud.tencent.com/tcb/scf?envId=offercome2025-9g14jitp22f4ddfc"
echo ""
echo "2. 找到函数 'api' (ID: lam-ccq8f9ez)"
echo ""
echo "3. 点击 '触发器' 标签"
echo ""
echo "4. 点击 '创建触发器'"
echo ""
echo "5. 配置触发器："
echo "   - 触发器类型: HTTP"
echo "   - 请求方法: 全部"
echo "   - 路径: /*"
echo "   - 启用: 是"
echo ""
echo "6. 点击 '确定' 创建触发器"
echo ""
echo "7. 复制触发器URL"
echo ""

echo "🔧 解决方案2: 使用API网关"
echo "=========================="
echo ""
echo "如果HTTP触发器配置失败，可以尝试API网关："
echo ""
echo "1. 访问API网关控制台："
echo "   https://console.cloud.tencent.com/apigateway"
echo ""
echo "2. 创建新的API网关服务"
echo ""
echo "3. 创建API，后端选择CloudBase函数"
echo ""
echo "4. 配置路径映射到您的函数"
echo ""

echo "🔧 解决方案3: 使用CloudBase CLI创建触发器"
echo "=========================================="
echo ""
echo "尝试使用新的CLI命令："
echo "tcb fn trigger create api --type http --config trigger-config.json"
echo ""

echo "🧪 测试当前函数"
echo "==============="
echo ""
echo "测试函数是否正常工作："
cloudbase functions:invoke api

echo ""
echo "📝 更新前端页面"
echo "==============="
echo ""
echo "1. 获取触发器URL后，运行："
echo "   ./update-frontend-url.sh"
echo ""
echo "2. 或者手动更新文件："
echo "   public/cost-dashboard-fixed.html (第355行)"
echo ""

echo "🌐 测试页面"
echo "==========="
echo ""
echo "1. API代理测试页面："
echo "   https://offercome2025-9g14jitp22f4ddfc-1256790827.tcloudbaseapp.com/api-proxy.html"
echo ""
echo "2. 成本监控面板："
echo "   https://offercome2025-9g14jitp22f4ddfc-1256790827.tcloudbaseapp.com/cost-dashboard-fixed.html"
echo ""

echo "📊 部署静态文件"
echo "==============="
echo ""
echo "重新部署静态文件："
cloudbase hosting:deploy public/ -e offercome2025-9g14jitp22f4ddfc

echo ""
echo "✅ 完整解决方案已准备就绪！"
echo ""
echo "📞 如果遇到问题："
echo "1. 检查CloudBase控制台中的函数状态"
echo "2. 确认触发器配置正确"
echo "3. 查看函数日志：cloudbase functions:log api"
echo "4. 测试函数调用：cloudbase functions:invoke api"
echo ""
echo "🎯 下一步：按照上述步骤配置HTTP触发器" 