#!/bin/bash

echo "🔧 配置CloudBase HTTP触发器..."
echo "=================================="

echo "📋 当前函数状态:"
cloudbase functions:list

echo ""
echo "🔗 创建HTTP触发器..."
echo "请按照以下步骤操作："
echo ""
echo "1. 访问CloudBase控制台："
echo "   https://console.cloud.tencent.com/tcb/scf?envId=offercome2025-9g14jitp22f4ddfc"
echo ""
echo "2. 找到函数 'api' (ID: lam-ccq8f9ez)"
echo ""
echo "3. 点击 '触发器' 标签"
echo ""
echo "4. 点击 '创建触发器'"
echo ""
echo "5. 配置触发器："
echo "   - 触发器类型: HTTP"
echo "   - 请求方法: 全部"
echo "   - 路径: /*"
echo "   - 启用: 是"
echo ""
echo "6. 点击 '确定' 创建触发器"
echo ""
echo "7. 复制触发器URL，格式类似："
echo "   https://service-xxxxx-1256790827.ap-shanghai.apigateway.myqcloud.com/release/api"
echo ""
echo "8. 更新前端页面中的URL"
echo ""

echo "📝 更新前端页面URL的步骤："
echo "1. 打开 public/cost-dashboard-fixed.html"
echo "2. 找到第355行的url配置"
echo "3. 将URL替换为新的触发器URL"
echo "4. 重新部署静态文件"
echo ""

echo "🚀 重新部署静态文件："
echo "cloudbase hosting:deploy public/ -e offercome2025-9g14jitp22f4ddfc"
echo ""

echo "✅ 配置完成后，前端页面就能正常访问CloudBase函数了！" 